Sprint 1/step 1
tokarev-yuriy/react-burger pull request #1
Opened 2022-10-31 11:17 UTC by tokarev-yuriy

Спринт - 1, этап - 1

2022-10-31 11:34 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                </div>
**Можно лучше:** Лого тоже можно обернуть в ссылку, это частая практика на проектах.

2022-10-31 11:49 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.
Приложение начинает обрастать функционалом и уже постепенно проглядывается картина готового продукта.

### **Вы молодец!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;

### **Но есть несколько замечаний, которые нужно исправить:**

- По макету, в app-header, первая ссылка должны быть активной.

- В компоненте `burger-constructor` булки должны быть одинаковыми.

- В директории `components` должен быть компонент App. Компонент `App`, как правило, это основной компонент в React, который выступает в качестве контейнера для всех остальных компонентов;

- Нужно очистить корневую директорию от лишних файлов, которые остались при инициализации create-react-app.

- В описании propTypes компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается.
  Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

  Пример как правильно:

  ```js
  data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
  ```

### **Сделает код лучше:**

- Используйте функциональные компоненты.

- При клике на таб, делать плавный скролл. Сейчас при разработке на React стремятся отдавать предпочтение функциональным компонентам, эти компоненты в проекте можно легко переписать как функциональные с использованием хуков.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

- Также заметил несколько слов написанных с ошибками. Чтобы это происходило реже попробуйте попользоваться расширением spell checker. https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +                </div>
**Можно лучше:** Лого тоже можно обернуть в ссылку, это частая практика на проектах.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
**Надо исправить:** Для подсчёта стоимости лучше использовать простую переменную, в будущем когда вы изучите `useMemo`, сможете обернуть этот кусок кода в useMemo, и тогда, у вас не будет вычисляться цена при каждом ререндере.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/utils/data.js
> +    image_mobile: PropTypes.string.isRequired,
**Надо исправить:** У ингредиента намного больше параметров.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/utils/data.js
> +const ingredientPropTypes = PropTypes.shape({
**Можно лучше:** Лучше вынести в отдельный файл, например `prop-types.js`.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +};
**Надо исправить:**
Здесь и во всём проекте.
В описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается.
Необходимо указывать .isRequired как у элемента массива, так и у самого массива в propTypes.

Пример как правильно:

```js
data: PropTypes.arrayOf(ingredientTypes.isRequired).isRequired;
```

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        let types = [
**Надо исправить:** 

если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <div style={{ display: 'flex' }} className="mb-10">
**Надо исправить:**

Не стоит писать стили инлайново, в будущем это может затруднить поиск ошибок, и перебить стили заданные классами. Лучше дать какой-то класс, и там указать уже нужные вам стили.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                    if (ingredient.type!=type.code) return;
**Надо исправить:** Делайте фильтрацию до `jsx` Вот так: 

```js
const buns = this.props.burgerData.filter((data) => data.type === 'bun');
const sauces = this.props.burgerData.filter((data) => data.type === 'sauce');
const main = this.props.burgerData.filter((data) => data.type === 'main');
```

Используйте только строгие равенства.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    items: PropTypes.arrayOf(ingredientPropTypes),
**Надо исправить:** Описал похожее замечание в `burger-constructor`.

2022-10-31 11:49 UTC, ArslanDev666 commented on src/components/burger-ingredients-item/burger-ingredients-item.jsx
> +    item: ingredientPropTypes
**Надо исправить**

в описании propTypes этого и других компонентов нужно указывать .isRequired у пропсов, без этого не контролируется, что пропс передается

Проверьте во всем проекте

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/components/burger-ingredients-item/burger-ingredients-item.jsx
> +    item: ingredientPropTypes
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    items: PropTypes.arrayOf(ingredientPropTypes),
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/components/app-header/app-header.jsx
> +                </div>
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/components/burger-constructor/burger-constructor.jsx
> +    }
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/utils/data.js
> +    image_mobile: PropTypes.string.isRequired,
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/utils/data.js
> +const ingredientPropTypes = PropTypes.shape({
спасибо, исправил

2022-11-04 23:03 UTC, tokarev-yuriy commented on src/components/burger-constructor/burger-constructor.jsx
> +};
спасибо, исправил

2022-11-04 23:04 UTC, tokarev-yuriy commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        let types = [
спасибо, исправил

2022-11-04 23:04 UTC, tokarev-yuriy commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <div style={{ display: 'flex' }} className="mb-10">
спасибо, исправил

2022-11-04 23:04 UTC, tokarev-yuriy commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                                    if (ingredient.type!=type.code) return;
спасибо, исправил

2022-11-12 12:04 UTC, merged