Sprint 1/step 2
tokarev-yuriy/react-burger pull request #2
Opened 2022-11-05 20:15 UTC by tokarev-yuriy

Sprint 1/step 2

2022-11-06 16:27 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец! Практически все замечания с прошлого ревью были исправлены.**

### **Но есть несколько замечаний, которые нужно исправить:**

- В компоненте `burger-constructor` булки не должны быть в ингредиентах.

- Поставьте атрибут href ссылкам.

### **Сделает код лучше:**

- Сделайте плавный скролл при клике на таб.

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2022-11-06 16:27 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +      }
**Вы молодец:** Очень хорошо сделали обработку ошибок.

2022-11-06 16:27 UTC, ArslanMustafin commented on src/components/app/app.jsx
> +        let data = await getIngredientsService();
**Можно лучше:**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как `const`.

2022-11-06 16:27 UTC, ArslanMustafin commented on src/api/ingredients.js
> +    let resp = await fetch(endpoints.ingredients);
**Надо исправить:**

Если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

<!--  -->

**Надо исправить:**

Добавьте проверку ответа сервера - res.ok:

Например:

```js
.then(res => res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
```

иначе сейчас, если сервер ответит не кодом 2xx, а какой либо ошибкой (4xx, 5xx) мы не попадем в catch т.к. в этом случае fetch не выбрасывает ошибку, мы попытаемся отрисовать данные, хотя они не пришли, в итоге на попытке отрисовки несуществующих данных упадет все приложение

[https://learn.javascript.ru/fetch](https://learn.javascript.ru/fetch)

[https://developer.mozilla.org/en-US/docs/Web/API/Response/ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok)

Т.к. эта проверка нужна у всех запросов, лучше вынести её в отдельную функцию

```js
const checkReponse = (res) => {
  return res.ok ? res.json() : res.json().then((err) => Promise.reject(err));
};
```

`fetch(someUrl).then(checkReponse)`

2022-11-06 16:27 UTC, ArslanMustafin commented on src/api/ingredients.js
> + */
**Вы молодец:** Круто, что вы документируете код.

2022-11-06 16:27 UTC, ArslanMustafin commented on src/api/endpoints.js
> +    ingredients: "https://norma.nomoreparties.space/api/ingredients"
**Можно лучше:** 

вынесите базовый адрес сервера `https://norma.nomoreparties.space/api` сервера в константу, а адрес эндпоинта можно оставить в самой функции запроса `${BURGER_API_URL}/ingredients`. В вашем случае, можно сделать просто константу, а список сделать вот так: 

```js
const endpoints = {
    ingredients: `${BURGER_API_URL}/ingredients`.
}
```

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/app-header/app-header.jsx
> +            <a className={styles.header_logo} >
**Надо исправить:** 

Здесь и далее. У ссылок должен быть атрибут href. Можно например указать `href="/"`. В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/app-nav-link/app-nav-link.jsx
> +        <a className={props.active ? styles.nav_link_active : styles.nav_link}>
**Надо исправить:** 

У ссылок должен быть атрибут href. Можно например указать `href="/"`. В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [props.bun, props.mainItems]);
**Можно лучше:** 

Нам не нужны тут зависимости, т.к в колбэке ничего не использует из того, что меняется.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +        });
**Надо исправить:** 

Тут лучше использовать метод forEach. map нужен для того чтобы изменять какие-либо элементы у массива.
map - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map
forEach - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.jsx
> +                    text={props.bun.name}
**Надо исправить:** 

По макету у булок должна быть приписка `верх, низ`.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/app/app.jsx
> +                mainItems={items.slice(1, items.length-1)}
**Надо исправить:** 

Там всё ещё есть 1 булка, лучше выполнить фильтрацию и поиск элемента.

```js
const bun = items.find(ingredient => ingredien.type === 'bun');
const ingredients = items.filter(ingredient => ingredien.type !== 'bun');
```

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/burger-constructor-total/burger-constructor-total.jsx
> +        event.preventDefault();
**Можно лучше:** Немного не понял зачем тут останавливать всплытие, и дефолтное событие.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const types = [
**Можно лучше:** Лучше обернуть в useMemo, чтобы не было повторных вычислений при ререндере.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +        if (event.key == "Escape") {
**Можно лучше:** 

лучше всегда использовать строгое сравнение `===` и строгое неравенство `!==`, это избавит от некоторых неявных ошибок связанных с приведением типов (например при использовании нестрогого сравнения выражение `0 == ""` вернет `true`, что не всегда ожидаемо, а выражение `0 === ""` вернет `false` т.к. типы у значений слева и справа разные, слева тип `number`, а справа тип `string`)

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +            event.preventDefault();
**Можно лучше:** 
 **Здесь и в похожих местах.** 
 
 А вот тут, тоже не оч понятно, зачем всё сбрасывать.

2022-11-06 16:27 UTC, ArslanDev666 commented on src/components/modal/modal.jsx
> +        </div>,
**Можно лучше:** 

Может быть лучше сделать вот так, тогда не будет нужно заботиться о всплытии событий:

```js
<> 
  <div className={styles.modal}> {/** ... */} </div> 
  <ModalOverlay onClose={onClose} />
</>
```

2022-11-06 18:05 UTC, tokarev-yuriy commented on src/components/app/app.jsx
> +      }
Спасибо

2022-11-06 18:05 UTC, tokarev-yuriy commented on src/components/app/app.jsx
> +        let data = await getIngredientsService();
Поправил

2022-11-06 18:06 UTC, tokarev-yuriy commented on src/api/ingredients.js
> +    let resp = await fetch(endpoints.ingredients);
Спасибо, добавил такую функцию

2022-11-06 18:06 UTC, tokarev-yuriy commented on src/api/ingredients.js
> + */
Спасибо

2022-11-06 18:06 UTC, tokarev-yuriy commented on src/api/endpoints.js
> +    ingredients: "https://norma.nomoreparties.space/api/ingredients"
Вынес константу в отдельный файл

2022-11-06 18:06 UTC, tokarev-yuriy commented on src/components/app-header/app-header.jsx
> +            <a className={styles.header_logo} >
Добавил ссылки

2022-11-06 18:07 UTC, tokarev-yuriy commented on src/components/app-nav-link/app-nav-link.jsx
> +        <a className={props.active ? styles.nav_link_active : styles.nav_link}>
Добавил ссылки

2022-11-06 18:07 UTC, tokarev-yuriy commented on src/components/burger-constructor/burger-constructor.jsx
> +    }, [props.bun, props.mainItems]);
Спасибо, убрал

2022-11-06 18:07 UTC, tokarev-yuriy commented on src/components/burger-constructor/burger-constructor.jsx
> +        });
Заменил на foreach

2022-11-06 18:07 UTC, tokarev-yuriy commented on src/components/burger-constructor/burger-constructor.jsx
> +                    text={props.bun.name}
добавил

2022-11-06 18:07 UTC, tokarev-yuriy commented on src/components/app/app.jsx
> +                mainItems={items.slice(1, items.length-1)}
Добавил фильтрацию

2022-11-06 18:08 UTC, tokarev-yuriy commented on src/components/burger-constructor-total/burger-constructor-total.jsx
> +        event.preventDefault();
Убрал

2022-11-06 18:08 UTC, tokarev-yuriy commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const types = [
Спасибо, обернул

2022-11-06 18:08 UTC, tokarev-yuriy commented on src/components/modal/modal.jsx
> +        if (event.key == "Escape") {
Спасибо, заменил

2022-11-06 18:14 UTC, tokarev-yuriy commented on src/components/modal/modal.jsx
> +            event.preventDefault();
Это была защита от компонента BurgerIngredientsItem.
Там висел обработчик клика на корневом div (по клику открытие модального окна с деталями).

И при этом сам компонент Modal был внутри этого div. 
Из-за этого клик по modalOverlay и modal проскакивал в BurgerIngredientsItem и опять открывал окно.

Я переработал этот момент в коммите [https://github.com/tokarev-yuriy/react-burger/pull/2/commits/989d3218d711b4b1c27469a5b81665f2758c318a](https://github.com/tokarev-yuriy/react-burger/pull/2/commits/989d3218d711b4b1c27469a5b81665f2758c318a)

2022-11-06 18:15 UTC, tokarev-yuriy commented on src/components/modal/modal.jsx
> +        </div>,
Это была защита от компонента BurgerIngredientsItem.
Там висел обработчик клика на корневом div (по клику открытие модального окна с деталями).

И при этом сам компонент Modal был внутри этого div. 
Из-за этого клик по modalOverlay и modal проскакивал в BurgerIngredientsItem и опять открывал окно.

Я переработал этот момент в коммите [https://github.com/tokarev-yuriy/react-burger/pull/2/commits/989d3218d711b4b1c27469a5b81665f2758c318a](https://github.com/tokarev-yuriy/react-burger/pull/2/commits/989d3218d711b4b1c27469a5b81665f2758c318a)

2022-11-07 15:20 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа 🔥

Все замечания с прошлого ревью были исправлены.

### **Работа принята! Удачи в дальнейшем обучении.**

2022-11-12 12:04 UTC, merged