Sprint 2/step 2
tokarev-yuriy/react-burger pull request #4
Opened 2022-11-20 00:44 UTC by tokarev-yuriy

Sprint 2/step 2

2022-11-20 04:03 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа!

### **Вы молодец!**

- Реализована работа с redux.

- Реализован функционал с использованием DnD.

### **Но есть несколько замечаний, которые нужно исправить:**

- У вас есть небольшой баг с DnD, нельзя поменять местами любой из ингредиентов с последним: https://disk.yandex.ru/i/YhSFZPZANHwvyg;

- Надо запретить нажимать на кнопку `Оформить заказ`, пока у вас нету булки и хотя бы 1 ингредиента.

- У вас не работает запрос `POST /order`, т.к у вас не прописаны нужные хедеры.

  ```js
    headers: {
      "Content-Type": "application/json;charset=utf-8",
    },
  ```

  А также у вас не открывается модальное окно, после успешного выполнения запроса `POST /order`.

- Cледует разделить экшены по файлам, на нас есть несколько задач (доменных областей) не связанных между собой - загрузка ингредиентов, оформление заказа, работа конструктор. Лучше, что бы экшены относящиеся к решению каждой были описаны в своем файле, т.к. приложение со времени будет развиваться, будет добавлять новый функционал и плохо, если придется все экшены описывать в одном файле, он будет слишком большой

  В текущем приложении можно разделить на следующие файлы:

  - загрузка данных ингредиентов
  - работа конструктора
  - открытие ингредиента в попапе
  - оформление заказа

- Со временем приложение будет разрастаться, появится новый функционал, если все будет в одном редьюсере (у вас не в одном, но всё же лучше разделить) он станет слишком большим, разделите один большой редьюсер на несколько, обрабатывающие данные одной предметной области (одного "домена"), например:

  - загрузка данных ингредиентов
  - отправка заказа
  - работа конструктора
  - открытие модального окна ингредиента

  Для объединения редьюсеров используйте combineReducers
  https://redux.js.org/api/combinereducers

### **Сделает код лучше:**

- Сделать плавный скролл, при нажатии на таб.

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2022-11-20 04:03 UTC, ArslanMustafin commented on src/services/actions/constructor.js
> +      let ingredients = [state.cart.bun._id, ...state.cart.ingredients.map(item => item._id), state.cart.bun._id];
**Надо исправить:**

если переменная не перезаписывается, то её следует объявлять как `const`, обратите внимание, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а изменяют только их внутреннее состояние, поэтому их так же нужно объявлять как `const`

2022-11-20 04:03 UTC, ArslanMustafin commented on src/services/reducers/constructor.js
> +        return {...state, ingredients: [...state.ingredients, {...action.item, id: guuid()}]}
**Надо исправить:** 

генерировать `id`, нужно в самом экшене, редьюсер должен быть чистой функцией.

2022-11-20 04:03 UTC, ArslanDev666 commented on src/services/reducers/constructor.js
> +          {...src, id: guuid()},
**Надо исправить:**

Ставьте пожалуйста скобки и отступы, а то читать код становится в разы труднее.

Также алгоритм лучше реализовать следующим образом (чтобы не было генераций uuid, а также бага с последним элементом): 

```js
      const hoverIndex = state.ingredients.findIndex((item) => item.id === action.src);
      const dragIndex = state.ingredients.findIndex((item) => item.id === action.dest);

      const updateData = [...state.ingredients];
      updateData.splice(hoverIndex, 0, updateData.splice(dragIndex, 1)[0]);

      return {
        ...state,
        ingredients: updateData,
      };
```

2022-11-20 04:03 UTC, ArslanDev666 commented on src/index.jsx
> +const store = createStore(rootReducer, enhancer);
**Можно лучше:**

Лучше перенести в файлик `services/index.js`.

2022-11-20 22:49 UTC, tokarev-yuriy commented on src/index.jsx
> +const store = createStore(rootReducer, enhancer);
спасибо, перенес

2022-11-20 22:49 UTC, tokarev-yuriy commented on src/services/reducers/constructor.js
> +          {...src, id: guuid()},
Спасибо, поправил алгоритм и отступы

2022-11-20 22:49 UTC, tokarev-yuriy commented on src/services/reducers/constructor.js
> +        return {...state, ingredients: [...state.ingredients, {...action.item, id: guuid()}]}
Исправил

2022-11-20 22:49 UTC, tokarev-yuriy commented on src/services/actions/constructor.js
> +      let ingredients = [state.cart.bun._id, ...state.cart.ingredients.map(item => item._id), state.cart.bun._id];
Исправил

2022-11-20 22:52 UTC, tokarev-yuriy commented
- Исправил замечания по коду и багу с DnD,
- Поправил запрос и отображение заказа,
- Разнес actions по 4-м хранилищам

2022-11-21 03:46 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Все замечания с прошлого ревью были исправлены 🔥.

### **Вы молодец!🔥 Работа принята, удачи в дальнейшем обучении.**

### **Сделает код лучше:**

- В счётчике булок отображать `2`, а не `1`, мы ведь считаем их как 2 штуки.

2022-12-01 15:44 UTC, merged